### PR TITLE
fix: dashboard suiciding due to ignoring symlinks

### LINKED ISSUE #2891: "kill other instance" logic incompatible with symlinks on Windows
## Description
currently we have these lines for killing other instances:
https://github.com/alvr-org/ALVR/blob/80f5c681ede81467d059c9cc22783ea80099cb93/alvr/dashboard/src/main.rs#L39-L47

However as [std docs says](https://doc.rust-lang.org/std/env/fn.current_exe.html#platform-specific-behavior:~:text=If%20the%20executable%20was%20invoked%20through%20a%20symbolic%20link%2C%20some%20platforms%20will%20return%20the%20path%20of%20the%20symbolic%20link%20and%20other%20platforms%20will%20return%20the%20path%20of%20the%20symbolic%20link%E2%80%99s%20target.)
> If the executable was invoked through a symbolic link, some platforms will return the path of the symbolic link and other platforms will return the path of the symbolic link’s target.

with the following dir structure:
```
├───alvr_streamer_windows
│   └───bin
│       └───win64
├───ALVR Dashboard.exe
└───i_am_a_symlink -> ./alvr_streamer_windows
```

On Windows the `self_path` is that in the symlink while the `other_path` is the real path, and then the process suicides.

I have modified servral lines for printing:
```diff
diff --git a/alvr/dashboard/src/main.rs b/alvr/dashboard/src/main.rs
index f327f366..28a787a2 100644
--- a/alvr/dashboard/src/main.rs
+++ b/alvr/dashboard/src/main.rs
@@ -38,11 +38,15 @@ fn main() {
 
     // Kill any other dashboard instance
     let self_path = std::env::current_exe().unwrap();
+    println!("self_path: {:?}", self_path);
     for proc in sysinfo::System::new_all().processes_by_name(OsStr::new(&afs::dashboard_fname())) {
         if let Some(other_path) = proc.exe()
-            && other_path != self_path
         {
-            proc.kill();
+            println!("other_path: {:?}", other_path);
+            if other_path != self_path {
+                println!("Killing other dashboard instance: {:?}", other_path);
+                proc.kill();
+            }
         }
     }
 ```

outputs:
```
self_path: "F:\\ALVR\\build\\i_am_a_symlink\\ALVR Dashboard.exe"
other_path: "F:\\ALVR\\build\\alvr_streamer_windows\\ALVR Dashboard.exe"
Killing other dashboard instance: "F:\\ALVR\\build\\alvr_streamer_windows\\ALVR Dashboard.exe"
```

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

## Environment

**OS Name and Version**: Microsoft Windows 11 Professional 10.0.26100 N/A Build 26100

### PR DESCRIPTION
**Pull request by The-personified-devil**
Fixes #2891

### CODE REVIEW

File: alvr/dashboard/src/main.rs [hunk 1]
```diff
@@ -44,9 +44,11 @@ fn main() {
     logging_backend::init_logging(server_events_sender.clone());
 
     // Kill any other dashboard instance
-    let self_path = std::env::current_exe().unwrap();
+    let self_path = std::env::current_exe().unwrap().canonicalize().unwrap();
```
Comment (zmerp) [inline alvr/dashboard/src/main.rs:47]: I guess you checked already, but is this canonicalize safe to unwrap?

**Review by zmerp — APPROVED** [review]

File: alvr/dashboard/src/main.rs (hunk 1 above)
Comment (The-personified-devil) [reply alvr/dashboard/src/main.rs:47]: I tested it and it works. Iirc on windows you can't delete an executable that's currently running (tho I'm not sure how that interacts with symlinks, but that depends on whether current_exe returns the symlink or the exe). So because the application will have the same privilege as what's needed to access the exe this should always work (the exe must exist and is accessible so it should resolve).

On linux you can delete the executable of a running application and it's fine (and especially a symlink to it) and that would cause the canonicalize to fail, tho I decided it's fine to fail in that scenario (if not better). The only thing that could realistically cause this tho would be that the executable is managed by a package manager that updates it whilst it's running. And in that scenario the alvr library loaded by steamvr would be mismatched so failing is probably better.

**Comment by The-personified-devil** [comment]
I love spurious ci failures.
