### PR TITLE
fix(sockets): :bug: Ignore error 997 (overlapped IO)

### LINKED ISSUE #1814: os error 997 (WSA_IO_PENDING) causes disconnection randomly
I tested with VRChat however probably causes with any applications.

## Description

The client randomly disconnects from the server with log os error 997.
According to [Microsoft documentation](https://learn.microsoft.com/en-us/windows/win32/winsock/windows-sockets-error-codes-2), Winsock error 997 is called WSA_IO_PENDING, which indicates requested system calls will be done lately. I think this is harmless, at least when I use UDP connections.
This may be caused by overload however my connection and system seem to have enough bandwidth for streaming. Anyway, I think WSA_IO_PENDING should be handled as a non-fatal disconnection.

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**: Ryzen 5 5500

**GPU**: Radeon RX 6600 XT

**GPU Driver Version**: 23.7.2

**Audio**: On-board configuration (High definition audio device)

**Network**: Windows 11 -> (Ethernet) -> Wi-fi router -> (5Ghz Wi-fi) -> Quest 2

### Installation
**ALVR Version**: 20.2.1 and [v21.0.0-dev00+nightly.2023.08.27](https://github.com/alvr-org/ALVR-nightly/releases/latest)

**ALVR Settings File**: Default setting, provided with the setup wizard. [session.json.txt](https://github.com/alvr-org/ALVR/files/12472395/session.json.txt)

**SteamVR Version**: 1.26.7

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc) - tested with stable
- [x] Portable (`zip`)  - tested with nigthly
- [x] Source

**OS Name and Version** : Windows 11 Home Build 22621.2134 (Japanese)

Log around error 997 from nightly: [session_log_around_error_997.txt](https://github.com/alvr-org/ALVR/files/12472466/session_log_around_error_997.txt)
Full Log: Too big to upload so I uploaded to Google Drive. [File](https://drive.google.com/file/d/1iTO2akLPzkXB0a_M27z1qDKQOY8JSoVV/view)
Translated error 997 log text from Japanese: `Client disconnected. Cause: Performing duplicate I/O operations. (os error 997)`
Log by local debug build: スクリーンショット 2023-08-30 181427

Sorry for my poor English and scarce knowledge.

### PR DESCRIPTION
**Pull request by zmerp**
Fixes #1814

### CODE REVIEW

File: alvr/common/src/connection_result.rs [hunk 1]
```diff
@@ -65,7 +65,10 @@ pub trait HandleTryAgain<T> {
 impl<T> HandleTryAgain<T> for io::Result<T> {
     fn handle_try_again(self) -> ConResult<T> {
         self.map_err(|e| {
-            if e.kind() == io::ErrorKind::TimedOut || e.kind() == io::ErrorKind::WouldBlock {
+            if e.kind() == io::ErrorKind::TimedOut
+                || e.kind() == io::ErrorKind::WouldBlock
+                || e.raw_os_error() == Some(997)
```
Comment (The-personified-devil) [inline alvr/common/src/connection_result.rs:70]: Should probably do this for windows only since error codes on linux differ completely

**Review by The-personified-devil — CHANGES_REQUESTED** [review]

File: alvr/common/src/connection_result.rs (hunk 1 above)
Comment (zmerp) [reply alvr/common/src/connection_result.rs:70]: Uh good call

**Review by The-personified-devil — APPROVED** [review]
