### PR TITLE
fix: missing libvpl.dll causes driver_alvr_server to crash

### LINKED ISSUE #3131: Nightly Release Wont Connect
I know it's the nightly and I get it, just wanna make sure someone knows about this, though I'm sure you guys already do, but all the recent ALVR nightly releases won't recognize when I launch steamvr starting on version 11. 22, 11. 19 seems to work so far, though I assume that gap in releases was maybe caused by this bug, I can't be sure.

### PR DESCRIPTION
**Pull request by luca-schlecker**
Bundles `libvpl.dll` with ALVR Dashboard just like the x264 libraries.
This should fix #3131. See that issue for further details.

### CODE REVIEW

File: alvr/xtask/src/build.rs [hunk 1]
```diff
@@ -199,6 +199,13 @@ pub fn build_streamer(
                 sh.copy_file(lib_path.clone(), bin_dir).unwrap();
             }
         }
+
+        // copy libvpl.dll
```
Comment (The-personified-devil) [inline alvr/xtask/src/build.rs:203]: This comment isn't needed, the code is self-explanatory.

**Comment by The-personified-devil** [comment]
Also, do you have any info on why just statically linking it didn't work?

**Comment by luca-schlecker** [comment]
> Please rebase on latest master, that should fix the misc errors CI is throwing.

Will do shortly 👍.

> PS: Sorry for taking this long, was a bit lazy during the holidays :) 

No worries, holidays are there to relax. 😁

> Also, do you have any info on why just statically linking it didn't work?

There was an issue with multiple definitions of functions from the standard library. I've corrected the clashing runtime versions (`MT` vs `MD`) but with no luck. It all just didn't work out on my end when linking statically. Could be that I just didn't align everything properly (runtime version, linkage type, etc.), maybe you have more luck.

After a few failed attempts I figured I could just go the dynamic route like the other libraries.

I can try again if you favor static linkage, but that would definitely have to wait till the end of the month as I am currently running low on spare time.

**Comment by zmerp** [comment]
Dynamic linking is fine. Static linking could come later if you want to work on it

**Comment by The-personified-devil** [comment]
> I can try again if you favor static linkage, but that would definitely have to wait till the end of the month as I am currently running low on spare time.

Totally fine as-is, I was just confused because the cargo stuff still contained the instructions to statically link vpl so I thought it was actually being linked (I'm assuming it was just left behind but didn't do anything cuz the lib wasn't there).

**Comment by zmerp** [comment]
@luca-schlecker nightly CI is failing for not finding libvpl.txt license

**Comment by luca-schlecker** [comment]
> @luca-schlecker nightly CI is failing for not finding libvpl.txt license

I will look into it immediately.

**Comment by luca-schlecker** [comment]
> @luca-schlecker nightly CI is failing for not finding libvpl.txt license

I believe to have found two issues:
1. The launcher cannot be built because the required libvpl license is missing. The launcher does not prepare the dependencies like the streamer, thus not downloading libvpl and its license.
2. The streamer cannot be built because `cargo-about` denies outputting to stdout in PowerShell.
```
[ERROR] cargo-about should not redirect its output in powershell, please use the -o, --output-file option to redirect to a file to avoid powershell encoding issues
```

I have put together #3173 which should fix both issues.
