### PR TITLE
fix(client_openxr): 🐛 Try fixing crash on Quest 2 related to multimodal

### LINKED ISSUE #2644: ALVR v20.12.0 infinite loading on Quest 2
## Description

Launching the ALVR app on Quest 2 results in infinite "three dots" loading screen. I believe this is a regression due to the fact that v20.11.1 works fine on my headset.

I've tried to go as early as possible in the ALVR Launcher app (v21.0.0.-dev01+nightly.2024.12.24) and the issue appears there too.
## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`
[`My hw-probe results`](https://linux-hardware.org/?probe=55f4b90949)

### Installation
**ALVR Version**:
v20.12.0
**ALVR Settings File**:
N/A due to the issue being related to the client, but I can provide it if for some reason it is needed.
**SteamVR Version**:
2.8.8
**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Arch Linux

### PR DESCRIPTION
**Pull request by zmerp**
Should fix #2644

### CODE REVIEW

File: alvr/client_openxr/src/interaction.rs [hunk 1]
```diff
@@ -108,17 +108,17 @@ pub struct InteractionContext {
     pub action_set: xr::ActionSet,
     pub button_actions: HashMap<u64, ButtonAction>,
     pub hands_interaction: [HandInteraction; 2],
-    pub multimodal_hands_enabled: bool,
+    pub multimodal_hands: Option<(MultimodalMeta, bool)>,
```
Comment (The-personified-devil) [inline alvr/client_openxr/src/interaction.rs:111]: This grouping is awful to read in every place it gets used. You could put the bool into the Meta struct itself?
I actually think having a non pub `multimodal_hands` and a pub `multimodal_hands_enabled` would actually still be the best, because the cognitive complexity nesting the bool into the option produces is not counteracted by the small improvement it brings (that I'll explain in another comment)

File: alvr/client_openxr/src/interaction.rs [hunk 2]
```diff
@@ -229,9 +229,13 @@ impl InteractionContext {
             "/user/hand/right/output/haptic",
         ));
 
+        let multimodal = create_ext_object("MultimodalMeta", Some(true), || {
+            MultimodalMeta::new(xr_session.clone(), &extra_extensions, xr_system)
```
Comment (The-personified-devil) [inline alvr/client_openxr/src/interaction.rs:233]: Clippy

File: alvr/client_openxr/src/extra_extensions/multimodal_input.rs [hunk 3]
```diff
@@ -39,60 +48,105 @@ pub type PauseSimultaneousHandsAndControllersTrackingMETA =
...
-            session.as_raw(),
-            &resume_info,
-        ))
-    }
+pub struct MultimodalMeta {
+    pub session: xr::Session<xr::AnyGraphics>,
+    pub resume_simultaneous_hands_and_controllers_tracking_meta:
+        ResumeSimultaneousHandsAndControllersTrackingMETA,
+    pub pause_simultaneous_hands_and_controllers_tracking_meta:
+        PauseSimultaneousHandsAndControllersTrackingMETA,
```
Comment (The-personified-devil) [inline alvr/client_openxr/src/extra_extensions/multimodal_input.rs:56]: Why are these pub?

File: alvr/client_openxr/src/extra_extensions/multimodal_input.rs [hunk 4]
```diff
@@ -12,11 +12,20 @@ pub const META_SIMULTANEOUS_HANDS_AND_CONTROLLERS_EXTENSION_NAME: &str =
...
 static TYPE_SIMULTANEOUS_HANDS_AND_CONTROLLERS_TRACKING_PAUSE_INFO_META: Lazy<xr::StructureType> =
     Lazy::new(|| xr::StructureType::from_raw(1000532003));
 
+#[repr(C)]
+pub struct SystemSymultaneousHandsAndControllersPropertiesMETA {
+    ty: xr::StructureType,
+    next: *const c_void,
+    supports_simultaneous_hands_and_controllers: sys::Bool32,
+}
+
```
Comment (The-personified-devil) [inline alvr/client_openxr/src/extra_extensions/multimodal_input.rs:28]: why is this pub?

File: alvr/client_openxr/src/interaction.rs [hunk 5]
```diff
@@ -371,9 +375,12 @@ impl InteractionContext {
...
         // First of all, disable/delete all sources. This ensures there are no conflicts
-        extra_extensions::pause_simultaneous_hands_and_controllers_tracking_meta(&self.xr_session)
-            .ok();
-        self.multimodal_hands_enabled = false;
+        if let Some((handle, enabled)) = &mut self.multimodal_hands {
+            if *enabled {
+                handle.pause().ok();
+                *enabled = false;
+            }
+        }
```
Comment (The-personified-devil) [inline alvr/client_openxr/src/interaction.rs:383]: If we just keep the multimodal_enables flag as a bool the this could become
```rust
self.multimodal_hands.map(|m| m.pause().ok());
enabled = false
```
Where we just do it unconditionally if we have multimodal support.

File: alvr/client_openxr/src/stream.rs [hunk 6]
```diff
@@ -510,12 +510,17 @@ fn stream_input_loop(
 
         // Note: When multimodal input is enabled, we are sure that when free hands are used
         // (not holding controllers) the controller data is None.
-        if int_ctx.multimodal_hands_enabled || left_hand_skeleton.is_none() {
+        let multimodal_enabled = int_ctx
+            .multimodal_hands
+            .as_ref()
+            .map(|(_, enabled)| *enabled)
+            .unwrap_or(false);
```
Comment (The-personified-devil) [inline alvr/client_openxr/src/stream.rs:517]: This is really bad, even a helper function would be better

File: alvr/client_openxr/src/interaction.rs [hunk 7]
```diff
@@ -407,14 +414,13 @@ impl InteractionContext {
...
-                &self.xr_session,
-            )
-            .is_ok()
-        {
-            self.multimodal_hands_enabled = true;
+        if config.body_tracking.is_none() && config.prefers_multimodal_input {
+            if let Some((handle, enabled)) = &mut self.multimodal_hands {
+                if !*enabled {
+                    handle.resume().ok();
+                    *enabled = true;
```
Comment (The-personified-devil) [inline alvr/client_openxr/src/interaction.rs:421]: This right here is the only place where having the bool nested would prevent any sort of programming bugs
and I think
```rust
if let Some(handle) = ... {
handle.resume().ok();
self.mm_enabled = true;
}
```
is easy enough to not mess up

File: alvr/client_openxr/src/interaction.rs (hunk 5 above)
Comment (The-personified-devil) [reply alvr/client_openxr/src/interaction.rs:383]: Advantage of always pausing it, even if it should already be paused is that we're not gonna run into any scenarios where it's still running for some reason and then we try to enable body tracking or something.
Since I'm pretty sure the issue wasn't pausing when it wasn't enabled, the issue was doing the xr call on devices that don't support it.

**Review by The-personified-devil — CHANGES_REQUESTED** [review]

File: alvr/client_openxr/src/extra_extensions/multimodal_input.rs (hunk 3 above)
Comment (zmerp) [reply alvr/client_openxr/src/extra_extensions/multimodal_input.rs:56]: Autocompletion + no brain

File: alvr/client_openxr/src/interaction.rs (hunk 1 above)
Comment (zmerp) [reply alvr/client_openxr/src/interaction.rs:111]: i'll keep the flag external. this was discussed before, we cannot create a stateful handle for SIMULTANEOUS_HANDS_AND_CONTROLLERS_EXTENSION because technically we could create a new second handle instance and that would mess things up

File: alvr/client_openxr/src/interaction.rs (hunk 5 above)
Comment (zmerp) [reply alvr/client_openxr/src/interaction.rs:383]: yup, we discussed this before

**Review by The-personified-devil — APPROVED** [review]
