### PR TITLE
fix: correctly parse active zones

### LINKED ISSUE #3021: Firewall Error (Linux, Bazzite)
I've never done a bug report on github before so sorry if I'm doing things wrong.
Every time i try to add firewall rules on Alvr 20.14.1 or even the nightly build  it errors out.
I opened the dashboard in terminal and it says:
Error: INVALID_ZONE: (default)
Error: INVALID_ZONE: (default)
Error: INVALID_ZONE: (default)
Error: INVALID_ZONE: (default)
[14:28:19.503 ERROR alvr_dashboard::data_sources] Setting firewall rules failed!
I'm pretty new to Linux (only have been using it since February) so maybe it's an issue on my end? I'm happy to try and give more info if possible! Thanks!

### PR DESCRIPTION
**Pull request by Remi4001**
ignores (default) after the default zone

fixes #3021

### CODE REVIEW

File: alvr/xtask/firewall/alvr_fw_config.sh [hunk 1]
```diff
@@ -10,7 +10,7 @@
 
 firewalld_cfg() {
     # Iterate around each active zone
-    for zone in $(firewall-cmd --get-active-zones | grep -P '^\w+'); do
```
Comment (The-personified-devil) [inline alvr/xtask/firewall/alvr_fw_config.sh:13]: The only part that seems to actually address what's going on is the `--only-matching` part. Can you explain what the reasoning behind the changes to the regex is/explain how the new regex works (working with grep regex is quite painful, so this would really help, if you actually understand what's going on).

Comment (Remi4001) [reply alvr/xtask/firewall/alvr_fw_config.sh:13]: I changed the regex because zones in firewalld can contain any of `_-/` plus alphanumeric characters from my little testing, but I couldn't find official documentation about what is allowed.
The change from PCRE (`-P`) to extended regexp (ERE) was because `\w` includes `_` in PCRE but not ERE, so I wanted to make it clear that `_` is matched in the regex, but, if you want to reduce changes, `grep -oP '^[\w/-]+'` will produce the same output.

Breakup of regex:
- `^` matches start of line
- `[[:alnum:]/_-]+` matches 1 or more consecutive characters (outer `[]`) from alphanumeric characters `[:alnum:]` + `/_-` (important, `-` must be at the end, because otherwise it is interpreted as a range, e.g. `a-z`)

Comment (The-personified-devil) [reply alvr/xtask/firewall/alvr_fw_config.sh:13]: I'd like `-P --only-matching` with the PCRE regex, because PCRE is actually available in tooling and much easier to find docs for. With that change this seems great.

And sorry for only reviewing so late.

Comment (Remi4001) [reply alvr/xtask/firewall/alvr_fw_config.sh:13]: No worries, should be good to merge now :)

**Review by The-personified-devil — APPROVED** [review]
